databases:
  - name: ProductionDB
    plan: free
    databaseName: onroad
    user: web_user

services:
  - type: web
    plan: free
    name: OnRoad
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_PROD_URL
        fromDatabase:
          name: ProductionDB
          property: postgres://web_user:6FYoTPLIUmTHdNpOElWEfjBpsybohKGx@dpg-cnoqh5v109ks73b9thsg-a.oregon-postgres.render.com/onroad
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.8
